FROM ubuntu:20.04

ENV TZ Asia/Tokyo
ENV LANG ja_JP.UTF-8
ENV NO_AT_BRIDGE 1

RUN apt-get update && \
    apt-get -y install --no-install-recommends tzdata
RUN apt-get -y install --no-install-recommends \
    libgtkmm-3.0-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    libwebkit2gtk-4.0-dev \
    g++ \
    make \
    language-pack-ja \
    fonts-takao \
    git \
    doxygen \
    graphviz
